name: Build and Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "doc/**"
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - "doc/**"

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          # Only a single commit is fetched by default, for the ref/SHA that
          # triggered the workflow. We need `fetch-depth: 0` to fetch all
          # history for all branches and tags.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Cache kubebuilder control plane binaries
        uses: actions/cache@v2
        with:
          path: test/bin
          key: ${{ runner.os }}-kubebuilder-${{ hashFiles('test/.kubebuilder-version') }}

      - name: Basic build
        run: make GO_BUILDFLAGS='-mod vendor'

      - name: Run tests with coverage
        run: make test-coverage

      - name: Upload coverage report to Coveralls
        run: |
          GO111MODULE=off go get -u github.com/mattn/goveralls
          goveralls -coverprofile=build/cover.out -service=github
        env:
          COVERALLS_TOKEN: ${{ github.token }}
